name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test
      - run: sh testdata/install-no-exec.sh
